kind: Service
apiVersion: v1
metadata:
  name: notes-app-service
  namespace: notes-space
spec:
  selector:
    app: notes-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8000
  type: LoadBalancer  
  

