name: aks_cluster
on: push
jobs:
    cluster:
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v4
            - name: Azure login
              run: az login --tenant add67cd2-c8b2-416c-b171-b61b22be92f4

            - name: terraform setup
              uses: hashicorp/setup-terraform@v3
            - name: terraform intialize
              run: cd module_practice && terraform init
            - name: terraform plan
              run: cd module_practice && terraform plan
            - name: terraform apply -auto-approve
              run: cd module_practice && terraform apply -auto-approve
            - name: connect cluster
              run: az aks get-credentials --resource-group trial-aks --name ritik-cluster --overwrite-existing
            - name: creating a namespace
              run: kubectl create namespace notes-space
            - name: running deploy file
              run: kubectl apply -f deployment.yml
            - name: running the service file
              run: kubectl apply -f service.yml
            #   add